name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Mondays at 9am UTC
    - cron: '0 9 * * 1'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pip-audit
      run: pip install pip-audit

    - name: Run security audit
      run: pip-audit -r requirements.txt --desc

    - name: Check for outdated packages
      run: |
        pip install -r requirements.txt
        pip list --outdated
